namespace QT_ChoiXanh_2.Models
{
    public class SelectItem
    {
        public int Id { get; set; }
        public string Text { get; set; }
    }

    public static class StaticData
    {
        public static List<SelectItem> Products => new List<SelectItem>
        {
            new SelectItem { Id = 0, Text = "Vui lòng chọn" },
            new SelectItem { Id = 35053, Text = "[35053] Chính sách đăng tin dành cho nhà tuyển dụng tại Tuyennhansu.vn" },
            new SelectItem { Id = 35055, Text = "[35055] Đánh giá nhân viên kinh doanh, cần phỏng vấn những gì" },
            new SelectItem { Id = 35056, Text = "[35056] Chính sách giải quyết tranh chấp" },
            new SelectItem { Id = 35057, Text = "[35057] Điều khoản sử dụng" },
            new SelectItem { Id = 35058, Text = "[35058] Nội dung email gửi cho quản trị và khách hàng" },
            new SelectItem { Id = 35059, Text = "[35059] Chính sách sử dụng cookie" },
            new SelectItem { Id = 35060, Text = "[35060] Chính sách xử lý dữ liệu" },
            new SelectItem { Id = 35061, Text = "[35061] Chính sách hoạt động và hợp tác" },
            new SelectItem { Id = 35112, Text = "[35112] Hướng dẫn cách chia sẻ kinh nghiệm trong hồ sơ xin việc" },
            new SelectItem { Id = 35115, Text = "[35115] Hướng dẫn chia sẻ kỹ năng làm việc để gây ấn tượng với nhà tuyển dụng" },
            new SelectItem { Id = 40002, Text = "[40002] Nhân viên tiếp tân, thư ký văn phòng" },
            new SelectItem { Id = 40003, Text = "[40003] Nhân viên kinh doanh thiết kế web" },
            new SelectItem { Id = 40004, Text = "[40004] CẦN TUYỂN NHÂN VIÊN KỸ THUẬT LAYOUT" },
            new SelectItem { Id = 40005, Text = "[40005] NHÂN VIÊN TƯ VẤN BẤT ĐỘNG SẢN" },
            new SelectItem { Id = 40006, Text = "[40006] Nhân viên sale admin mua bán, cho thuê nhà phố" },
            new SelectItem { Id = 40007, Text = "[40007] Nhân viên bán hàng qua điện thoại" },
            new SelectItem { Id = 40008, Text = "[40008] Nhân viên quản lý duyệt tin trang Web tuyennhansu.vn" },
            new SelectItem { Id = 40009, Text = "[40009] Nhân viên kế toán tiền lương" },
            new SelectItem { Id = 40012, Text = "[40012] Nhân viên Livestream bán hàng" },
            new SelectItem { Id = 40013, Text = "[40013] Nhân viên đăng tin và tìm khách" },
            new SelectItem { Id = 40014, Text = "[40014] Tuyển dụng nhân viên pháp lý, thành lập doanh nghiệp và các dịch vụ pháp lý khác" },
            new SelectItem { Id = 40015, Text = "[40015] NHÂN VIÊN KINH DOANH QUẢN LÝ TÒA NHÀ" },
            new SelectItem { Id = 40016, Text = "[40016] Cán bộ phụ trách tuyển dụng nội bộ" },
            new SelectItem { Id = 40017, Text = "[40017] NHÂN VIÊN MARKETING VÀ SEO" },
            new SelectItem { Id = 40018, Text = "[40018] NHÂN VIÊN KINH DOANH CHO THUÊ VĂN PHÒNG" },
            new SelectItem { Id = 40019, Text = "[40019] Cần tuyển giám sát cung ứng nhân sự" },
            new SelectItem { Id = 40031, Text = "[40031] Trưởng nhóm kinh doanh pháp lý" },
            new SelectItem { Id = 40034, Text = "[40034] NHÂN VIÊN HÀNH CHÍNH NHÂN SỰ" },
            new SelectItem { Id = 40035, Text = "[40035] TRƯỞNG NHÓM KINH DOANH THIẾT KẾ WEBSITE" },
            new SelectItem { Id = 40036, Text = "[40036] NHÂN VIÊN KẾ TOÁN" },
            new SelectItem { Id = 40140, Text = "[40140] Tuyển dụng nhân viên kinh doanh thiết kế web" },
            new SelectItem { Id = 40244, Text = "[40244] Hướng dẫn chia sẻ kỹ năng làm việc để gây ấn tượng với nhà tuyển dụng" },
            new SelectItem { Id = 40245, Text = "[40245] Hướng dẫn cách chia sẻ kinh nghiệm trong hồ sơ xin việc" },
            new SelectItem { Id = 40349, Text = "[khungkinh] Khung kính tranh xếp hình 2 x 2" },
            new SelectItem { Id = 40351, Text = "[khungmica] Khung mica tranh xếp hình 2 x 2" },
            new SelectItem { Id = 40353, Text = "[40353] Tranh xếp hình theo yêu cầu mảnh ghép 2 x 2" },
            new SelectItem { Id = 40354, Text = "[40354] Tranh xếp hình theo yêu cầu mảnh ghép 5 x 5" },
            new SelectItem { Id = 40355, Text = "[40355] Tranh xếp hình theo yêu cầu mảnh ghép 10 x 10" },
            new SelectItem { Id = 40364, Text = "[40364] Tranh xếp hình theo yêu cầu ngày Quốc tế Phụ nữ 8/3" },
            new SelectItem { Id = 40365, Text = "[khungkinh] Khung kính tranh xếp hình 5 x 5" },
            new SelectItem { Id = 40366, Text = "[40366] Khung mica tranh xếp hình 5 x 5" },
            new SelectItem { Id = 40367, Text = "[40367] Khung mica tranh xếp hình 10 x 10" },
            new SelectItem { Id = 40368, Text = "[40368] Khung kính tranh xếp hình 10 x 10" },
            new SelectItem { Id = 40369, Text = "[40369] Khung kính tranh xếp hình 20 x 20" },
            new SelectItem { Id = 40370, Text = "[40370] Khung mica tranh xếp hình 20 x 20" },
            new SelectItem { Id = 40376, Text = "[40376] Tranh xếp hình theo yêu cầu mảnh ghép 20 x 20" },
            new SelectItem { Id = 40495, Text = "[40495] Doanh nghiệp Nhà nước muốn tự chủ hơn, có không gian phát triển mới" },
            new SelectItem { Id = 40496, Text = "[40496] Đóng thuế kỷ lục 26,8 tỷ USD, nhà tiên tri xứ Omaha nhắc Chính phủ tiêu cho khéo" },
            new SelectItem { Id = 40499, Text = "[40499] Hai người bán bánh mì trả lại 100 triệu đồng nhặt được - Báo VnExpress" },
            new SelectItem { Id = 40505, Text = "[40505] Dòng xe VinFast Green có giá từ 269 triệu đồng - Báo VnExpress" },
            new SelectItem { Id = 40507, Text = "[40507] Dòng xe VinFast Green có giá từ 269 triệu đồng - Báo VnExpress" },
            new SelectItem { Id = 40509, Text = "[40509] Xanh SM ra mắt dịch vụ taxi chất lượng cao - Báo VnExpress" },
            new SelectItem { Id = 40515, Text = "[40515] Fernandes: `Man Utd còn cơ hội vô địch Europa League` - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40516, Text = "[40516] Zirkzee bật khóc khi Man Utd thua Fulham - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40517, Text = "[40517] Amorim: `Mục tiêu của Man Utd là vô địch Ngoại hạng Anh` - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40518, Text = "[40518] Khoảnh khắc tên lửa Iskander rải thảm đạn chùm xuống lữ đoàn Ukraine - Báo VnExpress" },
            new SelectItem { Id = 40519, Text = "[40519] Boeing phát hiện lỗi nứt thân trên máy bay tiếp dầu sắp giao cho Mỹ - Báo VnExpress" },
            new SelectItem { Id = 40520, Text = "[40520] Mỹ lần đầu công bố video `bom ninja` tập kích mục tiêu - Báo VnExpress" },
            new SelectItem { Id = 40521, Text = "[40521] Anh sẽ giúp Ukraine mua hơn 5.000 tên lửa chuyên hạ UAV Nga - Báo VnExpress" },
            new SelectItem { Id = 40522, Text = "[40522] Tàu sân bay Mỹ lần đầu đến Hàn Quốc trong nhiệm kỳ ông Trump - Báo VnExpress" },
            new SelectItem { Id = 40523, Text = "[40523] Chiến thuật `tạt sườn, cắt hậu cần` giúp Nga dồn ép Ukraine ở Kursk - Báo VnExpress" },
            new SelectItem { Id = 40524, Text = "[40524] Ứng viên bộ trưởng Mỹ bị ông Trump chất vấn giữa đêm vì chiến hạm hoen rỉ - Báo VnExpress" },
            new SelectItem { Id = 40525, Text = "[40525] UAV vũ trang Trung Quốc lần đầu áp sát Nhật Bản - Báo VnExpress" },
            new SelectItem { Id = 40526, Text = "[40526] Xe tăng Ukraine bùng cháy sau đòn tập kích của UAV Lancet - Báo VnExpress" },
            new SelectItem { Id = 40527, Text = "[40527] Mẫu UAV tự sát `không tiếng động` Nga triển khai ở Ukraine - Báo VnExpress" },
            new SelectItem { Id = 40529, Text = "[40529] Hàng nghìn người Chăm tảo mộ ở lễ Ramưwan - Báo VnExpress" },
            new SelectItem { Id = 40530, Text = "[40530] `Ăn núi ngủ rừng` trồng sâm Ngọc Linh - Báo VnExpress" },
            new SelectItem { Id = 40531, Text = "[40531] Ngư dân Phan Thiết trúng cá hố - Báo VnExpress" },
            new SelectItem { Id = 40532, Text = "[40532] Dỡ nhà nhường đất xây cao tốc Biên Hòa - Vũng Tàu - Báo VnExpress" },
            new SelectItem { Id = 40533, Text = "[40533] Hàng loạt kiốt khu nhà ở công nhân bị bỏ hoang - Báo VnExpress" },
            new SelectItem { Id = 40534, Text = "[40534] TP HCM dự kiến thu 164.000 tỷ sau di dời toàn bộ nhà ven kênh - Báo VnExpress" },
            new SelectItem { Id = 40535, Text = "[40535] Xe trên 16 chỗ `khuấy đảo` phố cổ Hà Nội - Báo VnExpress" },
            new SelectItem { Id = 40536, Text = "[40536] Đông nghịt người xuống đường hứng lộc Bà ở Bình Dương - Báo VnExpress" },
            new SelectItem { Id = 40537, Text = "[40537] Đặc phái viên `Tây học` có thể giúp Nga hàn gắn kinh tế với Mỹ - Báo VnExpress" },
            new SelectItem { Id = 40538, Text = "[40538] Bước ngoặt trong cuộc gặp Tổng thống Trump - Zelensky - Báo VnExpress" },
            new SelectItem { Id = 40539, Text = "[40539] Hỗn loạn trong nội các ông Trump trước tối hậu thư của Musk - Báo VnExpress" },
            new SelectItem { Id = 40540, Text = "[40540] Lý do ông Trump khao khát khoáng sản Ukraine - Báo VnExpress" },
            new SelectItem { Id = 40541, Text = "[40541] Quyền lực của DOGE châm ngòi tranh cãi nội bộ đảng Cộng hòa - Báo VnExpress" },
            new SelectItem { Id = 40542, Text = "[40542] Cuộc sống `địa ngục` của những người làm việc cho trung tâm lừa đảo - Báo VnExpress" },
            new SelectItem { Id = 40543, Text = "[40543] Tiềm năng khoáng sản 14.800 tỷ USD của Ukraine - Báo VnExpress" },
            new SelectItem { Id = 40544, Text = "[40544] Sóng ngầm phản đối ông Trump nhen nhóm trong đảng Cộng hòa - Báo VnExpress" },
            new SelectItem { Id = 40545, Text = "[40545] Việt kiều Hà Lan nỗ lực hòa nhập ở U17 Việt Nam - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40546, Text = "[40546] Al Nassr lo Ronaldo bị bắt ở Iran - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40547, Text = "[40547] Ramos ghi bàn đầu tiên sau 1 năm - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40548, Text = "[40548] Flick: `Không ai tin Barca có thể đua tranh ba danh hiệu` - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40549, Text = "[40549] Suarez kiến tạo 3 bàn trong chiến thắng của Miami - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40550, Text = "[40550] Guardiola chê bóng ở Cup FA - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40551, Text = "[40551] Neymar tỏa sáng rồi chấn thương - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40552, Text = "[40552] Man Utd bị loại khỏi Cup FA - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40553, Text = "[40553] Barca đòi lại đỉnh bảng La Liga với trận thắng đậm - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40559, Text = "[40559] Elon Musk nói về khả năng AI tiêu diệt nhân loại - Báo VnExpress Công nghệ" },
            new SelectItem { Id = 40560, Text = "[40560] Kênh HBO và Cinemax ngừng phát sóng trong gói HBO Go tại Việt Nam" },
            new SelectItem { Id = 40561, Text = "[40561] Internet di động Việt Nam tăng 15 bậc trên bảng xếp hạng thế giới - Báo VnExpress Công nghệ" },
            new SelectItem { Id = 40562, Text = "[40562] Đẩy mạnh thương mại hóa 5G để thúc đẩy tăng trưởng kinh tế - Báo VnExpress Công nghệ" },
            new SelectItem { Id = 40563, Text = "[40563] Công nghệ Việt hiện diện tại sự kiện lớn nhất ngành di động - Báo VnExpress Công nghệ" },
            new SelectItem { Id = 40564, Text = "[40564] Tiện ích mới khi thanh toán không tiền mặt trên Galaxy S25 Series - Báo VnExpress Công nghệ" },
            new SelectItem { Id = 40565, Text = "[40565] Xiaomi 15 Ultra về Việt Nam, giá 35 triệu đồng - Báo VnExpress Công nghệ" },
            new SelectItem { Id = 40566, Text = "[40566] Google phát triển chip cung cấp Internet qua ánh sáng - Báo VnExpress Công nghệ" },
            new SelectItem { Id = 40567, Text = "[40567] DeepSeek lần đầu hé lộ tỷ suất lợi nhuận của mô hình AI - Báo VnExpress Công nghệ" },
            new SelectItem { Id = 40568, Text = "[40568] Những lưu ý khi chọn mua máy hút ẩm - Báo VnExpress Công nghệ" },
            new SelectItem { Id = 40569, Text = "[40569] Robot hình người đang `tiến hóa` đến đâu? - Báo VnExpress Công nghệ" },
            new SelectItem { Id = 40570, Text = "[40570] Nhà sáng lập Google: Nhân viên nên làm 60 giờ mỗi tuần - Báo VnExpress Công nghệ" },
            new SelectItem { Id = 40572, Text = "[40572] 10 mỹ nhân mặc đẹp nhất Oscar 2025 - Báo VnExpress Giải trí" },
            new SelectItem { Id = 40573, Text = "[40573] Mick Jagger và bạn gái kém 44 tuổi dự tiệc hậu Oscar - Báo VnExpress Giải trí" },
            new SelectItem { Id = 40574, Text = "[40574] Bộ đầm đính 16.000 hạt pha lê của tỷ phú Selena Gomez - Báo VnExpress Giải trí" },
            new SelectItem { Id = 40575, Text = "[40575] Lisa và dàn sao Hollywood khoe sắc trên thảm đỏ Oscar - Báo VnExpress Giải trí" },
            new SelectItem { Id = 40576, Text = "[40576] Váy cưới đắp ren làm trong 720 giờ của Hà Trúc - Báo VnExpress Giải trí" },
            new SelectItem { Id = 40577, Text = "[40577] Sắc vóc diễn viên 26 tuổi tranh giải Oscar 2025 - Báo VnExpress Giải trí" },
            new SelectItem { Id = 40578, Text = "[40578] Song Hye Kyo tạo sức hút với trang phục ra sân bay - Báo VnExpress Giải trí" },
            new SelectItem { Id = 40579, Text = "[40579] Gu thời trang của Angelababy - Báo VnExpress Giải trí" },
            new SelectItem { Id = 40580, Text = "[40580] Tỷ phú Mark Zuckerberg hát, nhảy đón sinh nhật vợ - Báo VnExpress Giải trí" },
            new SelectItem { Id = 40581, Text = "[40581] Nhan sắc Demi Moore qua hơn 40 năm - Báo VnExpress Giải trí" },
            new SelectItem { Id = 40582, Text = "[40582] Người thấp bé mặc gì để trông cao hơn? - Báo VnExpress Giải trí" },
            new SelectItem { Id = 40584, Text = "[40584] Xe điện hóa Trung Quốc tăng trưởng mạnh nhờ thị trường châu Á - Báo VnExpress" },
            new SelectItem { Id = 40586, Text = "[40586] Những mẫu xe điện làm chủ nhân hài lòng nhất - Báo VnExpress" },
            new SelectItem { Id = 40587, Text = "[40587] Đền gần 1.000 cột ở Ấn Độ - Báo VnExpress Du lịch" },
            new SelectItem { Id = 40588, Text = "[40588] Crossover điện mới của Toyota lộ thiết kế - Báo VnExpress" },
            new SelectItem { Id = 40589, Text = "[40589] Sedan điện Volvo ES90 lộ thiết kế bản sản xuất - Báo VnExpress" },
            new SelectItem { Id = 40590, Text = "[40590] VinFast sắp có 63 xưởng dịch vụ xe điện tại Philippines - Báo VnExpress" },
            new SelectItem { Id = 40591, Text = "[40591] Series Parallel HEV - hệ thống hybrid mới của Yamaha - Báo VnExpress" },
            new SelectItem { Id = 40592, Text = "[40592] Miễn thi lý thuyết bằng lái xe máy A1, A nếu đã có bằng ôtô - Báo VnExpress" },
            new SelectItem { Id = 40594, Text = "[40594] Làm tranh điêu khắc bơ đón Tết ở Tây Tạng - Báo VnExpress Du lịch" },
            new SelectItem { Id = 40595, Text = "[40595] 8 lâu đài đẹp nhất châu Âu - Báo VnExpress Du lịch" },
            new SelectItem { Id = 40596, Text = "[40596] Biến đường hầm bí mật trong Thế chiến II thành điểm du lịch - Báo VnExpress Du lịch" },
            new SelectItem { Id = 40597, Text = "[40597] Công viên nhỏ nhất thế giới rộng bằng bốn tờ A4 - Báo VnExpress Du lịch" },
            new SelectItem { Id = 40598, Text = "[40598] Đền gần 1.000 cột ở Ấn Độ - Báo VnExpress Du lịch" },
            new SelectItem { Id = 40599, Text = "[40599] Làm tranh điêu khắc bơ đón Tết ở Tây Tạng - Báo VnExpress Du lịch" },
            new SelectItem { Id = 40600, Text = "[40600] Sân bay từng là nỗi khiếp sợ của hành khách - Báo VnExpress Du lịch" },
            new SelectItem { Id = 40601, Text = "[40601] Mùa tuyết ở Hokkaido - Báo VnExpress Du lịch" },
            new SelectItem { Id = 40602, Text = "[40602] 8 lâu đài đẹp nhất châu Âu - Báo VnExpress Du lịch" },
            new SelectItem { Id = 40603, Text = "[40603] Biến đường hầm bí mật trong Thế chiến II thành điểm du lịch - Báo VnExpress Du lịch" },
            new SelectItem { Id = 40604, Text = "[40604] Saigontourist Group ưu đãi mua sớm vé lễ hội ẩm thực 2025 - Báo VnExpress Du lịch" },
            new SelectItem { Id = 40605, Text = "[40605] 2.000 người sẽ dự lễ thắp nến tại Vesak 2025 trên núi Bà Đen - Báo VnExpress Du lịch" },
            new SelectItem { Id = 40606, Text = "[40606] Những trải nghiệm cho phái đẹp tại The Grand Ho Tram dịp 8/3 - Báo VnExpress Du lịch" },
            new SelectItem { Id = 40607, Text = "[40607] Bali bức xúc vì khách đi bụi ở lâu, tiêu ít - Báo VnExpress Du lịch" },
            new SelectItem { Id = 40608, Text = "[40608] Saigontourist Group ưu đãi mua sớm vé lễ hội ẩm thực 2025 - Báo VnExpress Du lịch" },
            new SelectItem { Id = 40609, Text = "[40609] Khám phá làng hương di sản ở Tây Ninh - Báo VnExpress Du lịch" },
            new SelectItem { Id = 40611, Text = "[40611] Vì sao chảy nước mũi khi ăn cay? - Báo VnExpress Sức khỏe" },
            new SelectItem { Id = 40612, Text = "[40612] Các thực phẩm giảm đau nửa đầu - Báo VnExpress Sức khỏe" },
            new SelectItem { Id = 40613, Text = "[40613] Dấu hiệu cảnh báo tắc nghẽn động mạch - Báo VnExpress Sức khỏe" },
            new SelectItem { Id = 40614, Text = "[40614] Bệnh gout khác viêm mô tế bào thế nào - Báo VnExpress Sức khỏe" },
            new SelectItem { Id = 40615, Text = "[40615] Bị suy giáp nên giảm cân thế nào? - Báo VnExpress Sức khỏe" },
            new SelectItem { Id = 40616, Text = "[40616] Có nên lọc chì trong máu? - Báo VnExpress Sức khỏe" },
            new SelectItem { Id = 40617, Text = "[40617] Điều gì xảy ra với cơ thể khi ăn hành tây? - Báo VnExpress Sức khỏe" },
            new SelectItem { Id = 40618, Text = "[40618] Bé trai tổn thương giác mạc sau nhiễm cúm - Báo VnExpress Sức khỏe" },
            new SelectItem { Id = 40619, Text = "[40619] Có con sau 8 năm vô sinh thứ phát - Báo VnExpress Sức khỏe" },
            new SelectItem { Id = 40620, Text = "[40620] Nhau thai ngoài màng đệm - Báo VnExpress Sức khỏe" },
            new SelectItem { Id = 40621, Text = "[40621] Nguyên nhân gây đau đầu thường gặp - Báo VnExpress Sức khỏe" },
            new SelectItem { Id = 40624, Text = "[40624] Chính sách nổi bật có hiệu lực từ tháng 3 - Báo VnExpress" },
            new SelectItem { Id = 40625, Text = "[40625] Kỹ sư cơ khí chuyển nghề làm nông nghiệp công nghệ cao - Báo VnExpress" },
            new SelectItem { Id = 40626, Text = "[40626] Quốc hội xem xét sửa Hiến pháp tại kỳ họp tháng 5 - Báo VnExpress" },
            new SelectItem { Id = 40627, Text = "[40627] Vì sao cần mở rộng không gian Hồ Gươm? - Báo VnExpress" },
            new SelectItem { Id = 40628, Text = "[40628] Xe máy phát nổ sau tai nạn, hai người chết - Báo VnExpress" },
            new SelectItem { Id = 40629, Text = "[40629] Thi thể hai cậu cháu bên đường - Báo VnExpress" },
            new SelectItem { Id = 40630, Text = "[40630] Bị tước bằng lái vì chạy ôtô ngược chiều trên cao tốc - Báo VnExpress" },
            new SelectItem { Id = 40631, Text = "[40631] Miền Bắc nồm ẩm trở lại - Báo VnExpress" },
            new SelectItem { Id = 40632, Text = "[40632] Kỹ sư cơ khí chuyển nghề làm nông nghiệp công nghệ cao - Báo VnExpress" },
            new SelectItem { Id = 40633, Text = "[40633] Nhiều doanh nghiệp muốn đầu tư nâng cấp sân bay Phú Quốc - Báo VnExpress" },
            new SelectItem { Id = 40634, Text = "[40634] Ông Nguyễn Văn Được: Metro sẽ giải quyết ùn tắc cho TP HCM hơn 10 triệu dân - Báo VnExpress" },
            new SelectItem { Id = 40635, Text = "[40635] Đề xuất xây cao tốc từ sân bay Long Thành đến Hồ Tràm - Báo VnExpress" },
            new SelectItem { Id = 40636, Text = "[40636] Cầu Nguyễn Hoàng bắc qua sông Hương trước ngày thông xe - Báo VnExpress" },
            new SelectItem { Id = 40637, Text = "[40637] Người đàn ông say xỉn lái ôtô lao vào đám cưới - Báo VnExpress" },
            new SelectItem { Id = 40638, Text = "[40638] Xe cứu thương cháy rụi trên cao tốc TP HCM - Trung Lương - Báo VnExpress" },
            new SelectItem { Id = 40639, Text = "[40639] Bộ Chính trị đồng ý mở rộng diện hưởng chính sách nghỉ hưu trước tuổi - Báo VnExpress" },
            new SelectItem { Id = 40640, Text = "[40640] Hợp long cầu nối Đà Nẵng với Quảng Nam - Báo VnExpress" },
            new SelectItem { Id = 40641, Text = "[40641] Loạt xe máy bị tông ngã rạp trên quốc lộ 51 - Báo VnExpress" },
            new SelectItem { Id = 40642, Text = "[40642] Dàn khí tài hiện đại của Công an trưng bày quanh Hồ Gươm - Báo VnExpress" },
            new SelectItem { Id = 40643, Text = "[40643] Khởi công kéo cáp ngầm từ Sóc Trăng cấp điện cho Côn Đảo - Báo VnExpress" },
            new SelectItem { Id = 40644, Text = "[40644] Hai nhà khoa học nữ được trao giải thưởng Kovalevskaia 2024 - Báo VnExpress" },
            new SelectItem { Id = 40645, Text = "[40645] Cục CSGT: Xe điện 4 bánh nhỏ chỉ nên chạy trong các điểm du lịch - Báo VnExpress" },
            new SelectItem { Id = 40646, Text = "[40646] 5 ôtô va chạm trên quốc lộ 1, người đi xe máy bị thương - Báo VnExpress" },
            new SelectItem { Id = 40647, Text = "[40647] Hà Nội dự kiến xây cầu cạn mở rộng đường ven Hồ Tây - Báo VnExpress" },
            new SelectItem { Id = 40648, Text = "[40648] Xây dựng phương án tinh gọn các hội quần chúng cấp tỉnh - Báo VnExpress" },
            new SelectItem { Id = 40649, Text = "[40649] Hải Phòng làm đường vành đai 2 gần 7.500 tỷ đồng - Báo VnExpress" },
            new SelectItem { Id = 40650, Text = "[40650] Hai nam sinh bị sóng biển cuốn mất tích - Báo VnExpress" },
            new SelectItem { Id = 40651, Text = "[40651] Tai nạn giao thông ở Thanh Hóa: Tông vào xe chở rác, hai người tử vong" },
            new SelectItem { Id = 40652, Text = "[40652] Doanh nghiệp dần cởi mở tuyển dụng lao động trung niên - Báo VnExpress" },
            new SelectItem { Id = 40653, Text = "[40653] `Hàm cá mập` - công trình gây tranh cãi hơn 30 năm - Báo VnExpress" },
            new SelectItem { Id = 40654, Text = "[40654] Đề xuất quy hoạch TP HCM có 6 phân vùng đô thị - Báo VnExpress" },
            new SelectItem { Id = 40655, Text = "[40655] Ngân sách dành thêm 10.000 tỷ đồng cho khoa học công nghệ - Báo VnExpress" },
            new SelectItem { Id = 40656, Text = "[40656] Xác định danh tính liệt sĩ sau 52 năm hy sinh - Báo VnExpress" },
            new SelectItem { Id = 40657, Text = "[40657] `Sản xuất lúa gạo gặp nhiều thách thức từ biến động thị trường quốc tế` - Báo VnExpress" },
            new SelectItem { Id = 40658, Text = "[40658] Quản lý báo chí `không phải để cấm mà kiến tạo phát triển` - Báo VnExpress" },
            new SelectItem { Id = 40659, Text = "[40659] Đề xuất cấm ngân hàng mua bán thông tin tín dụng của khách - Báo VnExpress" },
            new SelectItem { Id = 40660, Text = "[40660] Hiện trạng mặt bằng metro Bến Thành - Tham Lương trước khởi công - Báo VnExpress" },
            new SelectItem { Id = 40661, Text = "[40661] Hải Phòng, Đà Nẵng dừng xây dựng hai trụ sở cấp huyện - Báo VnExpress" },
            new SelectItem { Id = 40662, Text = "[40662] Ba tàu gặp nạn giữa sóng lớn trên biển Quảng Ngãi - Báo VnExpress" },
            new SelectItem { Id = 40663, Text = "[40663] Hiện trạng tòa nhà `Hàm cá mập` bên Hồ Gươm - Báo VnExpress" },
            new SelectItem { Id = 40664, Text = "[40664] Tai nạn liên hoàn ở cầu Ba Son - Báo VnExpress" },
            new SelectItem { Id = 40665, Text = "[40665] Cắm cọc ranh giải phóng mặt bằng cao tốc TP HCM - Mộc Bài - Báo VnExpress" },
            new SelectItem { Id = 40666, Text = "[40666] `Quản lý chặt chẽ tài sản, trụ sở cơ quan sau sắp xếp` - Báo VnExpress" },
            new SelectItem { Id = 40668, Text = "[40668] TP HCM dự kiến bắn pháo hoa 7 điểm dịp lễ 30/4 - Báo VnExpress" },
            new SelectItem { Id = 40669, Text = "[40669] Đề xuất 14.800 tỷ đồng xây cao tốc qua Hà Giang - Báo VnExpress" },
            new SelectItem { Id = 40670, Text = "[40670] Khoanh vùng 15 điểm có tiềm năng đất hiếm ở Tây Bắc - Báo VnExpress" },
            new SelectItem { Id = 40671, Text = "[40671] Mạng xã hội có thể không được yêu cầu người dùng cung cấp ảnh căn cước công dân - Báo VnExpress" },
            new SelectItem { Id = 40672, Text = "[40672] Đề xuất lập đơn vị hành chính mới: `Nội đô` tại Hà Nội, TP HCM - Báo VnExpress" },
            new SelectItem { Id = 40673, Text = "[40673] Bức phù điêu làm từ 300 kg muối - Báo VnExpress" },
            new SelectItem { Id = 40674, Text = "[40674] Bộ trưởng Quốc phòng yêu cầu đẩy nhanh tiến độ xây cầu Phong Châu mới - Báo VnExpress" },
            new SelectItem { Id = 40675, Text = "[40675] Bị phạt 151 triệu đồng vì cơi nới thùng xe, chở quá tải - Báo VnExpress" },
            new SelectItem { Id = 40676, Text = "[40676] Cửa ngõ TP HCM ùn tắc 5 km sau tai nạn - Báo VnExpress" },
            new SelectItem { Id = 40677, Text = "[40677] Hai nam sinh tử vong sau tai nạn - Báo VnExpress" },
            new SelectItem { Id = 40678, Text = "[40678] Cầu vượt gần một km nối ga T3 Tân Sơn Nhất trước thông xe - Báo VnExpress" },
            new SelectItem { Id = 40679, Text = "[40679] Cấm ôtô 15 ngày để sửa chữa cầu trên quốc lộ 1 - Báo VnExpress" },
            new SelectItem { Id = 40680, Text = "[40680] Hà Nội dự kiến phá bỏ tòa nhà `Hàm cá mập` - Báo VnExpress" },
            new SelectItem { Id = 40681, Text = "[40681] Khu đất bên Hồ Gươm dự kiến được quy hoạch làm không gian công cộng - Báo VnExpress" },
            new SelectItem { Id = 40682, Text = "[40682] Nghệ thuật nghi binh trong chiến dịch Tây Nguyên - Báo VnExpress" },
            new SelectItem { Id = 40683, Text = "[40683] Khu du lịch giữa hồ Trị An chưa có đánh giá tác động môi trường - Báo VnExpress" },
            new SelectItem { Id = 40684, Text = "[40684] 6 cống ngăn mặn nghìn tỷ ở miền Tây bị `treo` nhiều năm - Báo VnExpress" },
            new SelectItem { Id = 40685, Text = "[40685] Xe tải đấu đầu, hai người tử vong - Báo VnExpress" },
            new SelectItem { Id = 40686, Text = "[40686] Chelsea đẩy Man City khỏi top 4 Ngoại hạng Anh - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40687, Text = "[40687] Amorim: `Man Utd cần nhiều Fernandes hơn` - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40688, Text = "[40688] Man Utd rơi điểm trước Arsenal - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40689, Text = "[40689] Arteta bỏ dở phỏng vấn sau trận hòa Man Utd - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40690, Text = "[40690] Vinicius ghi tuyệt phẩm solo cho Real - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40691, Text = "[40691] Cựu võ sĩ quyền Anh khống chế kẻ dọa đánh bom sân bay - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40692, Text = "[40692] Atletico vỡ mộng dẫn đầu La Liga - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40693, Text = "[40693] Đồng hồ thể thao dự đoán thành tích chạy chính xác đến mức nào - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40694, Text = "[40694] Palmer lần đầu đá hỏng phạt đền ở Ngoại hạng Anh - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40695, Text = "[40695] Son Heung-min đá panenka cứu Tottenham - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40696, Text = "[40696] Đặng Văn Lâm: `Chuyện ở đội tuyển sẽ tính sau` - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40697, Text = "[40697] HAGL rơi chiến thắng ở phút 100 - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40698, Text = "[40698] Tân HLV Indonesia triệu tập gần 60% cầu thủ lai - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40699, Text = "[40699] Djokovic đổ lỗi cho sân đấu sau khi bị loại ở Indian Wells - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40700, Text = "[40700] Sân golf cho những người thích khỏa thân - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40701, Text = "[40701] Golfer Malaysia vô địch Women`s Amateur Asia Pacific - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40702, Text = "[40702] WTA thưởng tiền các tay vợt nữ sinh con - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40703, Text = "[40703] Haaland bị châm chọc sau thất bại của Man City - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40704, Text = "[40704] `Đặng Văn Lâm thiệt thòi khi xuống hạng Nhất` - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40705, Text = "[40705] Slot quát mắng cầu thủ Liverpool - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40706, Text = "[40706] Enrique: `PSG nguy hiểm hơn vì không còn gì để mất trước Liverpool` - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40707, Text = "[40707] Jeeno Thitikul - người mở đầu cho thế hệ golf Thái Lan thành công sau WAAP - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40708, Text = "[40708] Salah chạm kỷ lục của Henry, Haaland tại Ngoại hạng Anh - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40709, Text = "[40709] Guardiola: `Suất dự Champions League không từ trên trời rơi xuống` - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40710, Text = "[40710] Vì sao bài đá phạt của Arsenal không còn hiệu quả? - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40711, Text = "[40711] Hồng Lệ, Nguyên Thanh ‘hụt’ giải thưởng khủng - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40712, Text = "[40712] Djokovic lần thứ hai liên tiếp thua trận mở màn - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40713, Text = "[40713] Ferdinand: `Arsenal đang thụt lùi ở Ngoại hạng Anh` - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40714, Text = "[40714] Nữ runner Mỹ dùng gậy tiếp sức đánh đối thủ - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40715, Text = "[40715] Hàng công của Man Utd tệ thế nào - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40716, Text = "[40716] Bayern, Leverkusen, Dortmund cùng thua tại Bundesliga - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40717, Text = "[40717] Barca hoãn trận đấu vì bác sĩ đột tử - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40718, Text = "[40718] Liverpool hơn Arsenal 16 điểm tại Ngoại hạng Anh - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40719, Text = "[40719] Cộng đồng nói gì về VnExpress Marathon Volvo All-Star" },
            new SelectItem { Id = 40720, Text = "[40720] Quang Hải giúp Công an Hà Nội hòa Nam Định - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40721, Text = "[40721] Man City gục ngã trước Nottingham - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40722, Text = "[40722] Tiền đạo Tiến Linh chấn thương - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40723, Text = "[40723] Nguyễn Filip lỡ hẹn tuyển Việt Nam - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40724, Text = "[40724] Djokovic được ví như `Vua thể thao` - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40725, Text = "[40725] Zverev bật bãi sớm ở Indian Wells Masters - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40726, Text = "[40726] Long Biên Marathon 2025 hoãn tổ chức - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40727, Text = "[40727] Carragher: `Amorim đang chết chìm tại Man Utd` - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40728, Text = "[40728] Kyrgios lỡ hẹn Djokovic - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40729, Text = "[40729] Arteta: `Gặp Man Utd phải đá như khi thắng PSV` - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40730, Text = "[40730] Slot tận hưởng tuần lễ với 3 trận `chung kết` - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40731, Text = "[40731] Amorim: `Tôi sẽ không được trao nhiều thời gian như Arteta` - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40732, Text = "[40732] Quang Liêm xếp áp chót Prague Masters - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40733, Text = "[40733] Vì sao Alisson không phải là thủ môn hay nhất Ngoại hạng Anh mùa này? - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40734, Text = "[40734] Arsenal được dự đoán thắng Man Utd ở Ngoại hạng Anh - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40735, Text = "[40735] Thủ môn bị cấm 6 trận vì song phi, đạp vào mặt đối thủ ở Cup FA - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40736, Text = "[40736] HLV Hà Tĩnh bực bội khi đội nhà bị gọi là `Hòa Tĩnh` - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40737, Text = "[40737] Vì sao Indian Wells Masters 2025 khó lường? - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40738, Text = "[40738] Hà Hậu thắng vang dội ở Vietnam Ultra Marathon 2025 - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40739, Text = "[40739] Chúc An khó tạo bất ngờ ở giải golf nữ châu Á - Thái Bình Dương - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40740, Text = "[40740] Ronaldo không cứu nổi Al Nassr - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40741, Text = "[40741] Tại sao chuẩn thành tích đầu vào là xu hướng tất yếu của chạy bộ phong trào - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40742, Text = "[40742] Hà Nội FC bị Hà Tĩnh ngắt mạch thắng ở V-League - Báo VnExpress Thể thao" },
            new SelectItem { Id = 40743, Text = "[40743] Ryan Peake ..." },
            new SelectItem { Id = 48144, Text = "[48144] Chủ tịch Công ty Hải Hà dùng 317 tỉ đồng quỹ bình ổn giá xăng dầu sai quy định ra sao? - Tuổi Trẻ Online" },
            new SelectItem { Id = 48145, Text = "[48145] Khởi tố 4 bị can tuyển sinh sai vào trường nội trú ở Thanh Hóa - Tuổi Trẻ Online" },
            new SelectItem { Id = 48146, Text = "[48146] Lắp camera quay hoạt động của cảnh sát giao thông trên cao tốc để tống tiền - Tuổi Trẻ Online" },
            new SelectItem { Id = 48147, Text = "[48147] Khởi tố nguyên thứ trưởng Bộ Nông nghiệp và Phát triển nông thôn Hoàng Văn Thắng - Tuổi Trẻ Online" },
            new SelectItem { Id = 48148, Text = "[48148] Giao quản lý máy ủi thi công cao tốc, lại hút trộm dầu mang đi bán - Tuổi Trẻ Online" },
            new SelectItem { Id = 48149, Text = "[48149] Công an thông tin vụ bắt chủ tịch xã cùng 35kg ma túy, 4 bánh heroin - Tuổi Trẻ Online" },
            new SelectItem { Id = 48150, Text = "[48150] Say xỉn không chịu về, bị bạn nhậu dùng ly bia đập lên đầu tử vong - Tuổi Trẻ Online" },
            new SelectItem { Id = 48151, Text = "[48151] Hai nhóm người dùng súng bắn nhau giải quyết mâu thuẫn hầu tòa - Tuổi Trẻ Online" },
            new SelectItem { Id = 48152, Text = "[48152] Bị cáo Lê Thanh Vân nói `rất buồn vì bị bắt khi sắp mãn nhiệm kỳ đại biểu Quốc hội` - Tuổi Trẻ Online" },
            new SelectItem { Id = 48153, Text = "[48153] Ông Trần Đăng Tân làm chánh văn phòng TAND TP.HCM, ông Phạm Ngọc Duy làm chánh án TAND Tân Phú - Tuổi Trẻ Online" },
            new SelectItem { Id = 48154, Text = "[48154] Bắt bác sĩ bị tố hiếp dâm nữ bệnh nhân tại phòng khám - Tuổi Trẻ Online" },
            new SelectItem { Id = 48155, Text = "[48155] Mua nguyên liệu trên TikTok chế pháo nổ, thiếu niên giao nộp 151 viên pháo cho công an - Tuổi Trẻ Online" },
            new SelectItem { Id = 48156, Text = "[48156] Kẹt xe, nhiều người ở TP.HCM vẫn kiên nhẫn bật xi nhan, chừa lối đợi rẽ phải - Tuổi Trẻ Online" },
            new SelectItem { Id = 48157, Text = "[48157] Công an triệu tập nhóm xe ôm hỗn chiến trước Bệnh viện quận Bình Thạnh - Tuổi Trẻ Online" },
            new SelectItem { Id = 48158, Text = "[48158] 10 lỗi vi phạm nào khiến tài xế xe máy có thể bị phạt tới 10 triệu đồng? - Tuổi Trẻ Online" },
            new SelectItem { Id = 48159, Text = "[48159] Bắt 4 người đang mua bán, vận chuyển trái phép 1kg ma túy - Tuổi Trẻ Online" },
            new SelectItem { Id = 48160, Text = "[48160] Cảnh sát nổ súng bắt xe chở ma túy, trên xe có chủ tịch xã - Tuổi Trẻ Online" },
            new SelectItem { Id = 48161, Text = "[48161] Ông Lưu Bình Nhưỡng nói `đã cố gắng gột rửa những điều phạm phải, đặc biệt về tâm can` - Tuổi Trẻ Online" },
            new SelectItem { Id = 48162, Text = "[48162] Bắt nhóm giang hồ cộm cán cầm đầu đường dây buôn ma túy `khủng` liên tỉnh - Tuổi Trẻ Online" },
            new SelectItem { Id = 48163, Text = "[48163] Sáng nay tòa xử ông Trần Đình Triển tội lợi dụng quyền tự do dân chủ, 12 luật sư đăng ký bào chữa - Tuổi Trẻ Online" },
            new SelectItem { Id = 48164, Text = "[48164] Ghi họ cha là tên nước ngoài rồi chú thích thêm bằng tiếng Việt được không? - Tuổi Trẻ Online" },
            new SelectItem { Id = 48165, Text = "[48165] 15% di sản của cố nghệ sĩ Vũ Linh chia em gái gồm những gì? - Tuổi Trẻ Online" },
            new SelectItem { Id = 48166, Text = "[48166] Phạm nhân chết chưa rõ nguyên nhân tại trại giam Công an tỉnh Kiên Giang - Tuổi Trẻ Online" },
            new SelectItem { Id = 48167, Text = "[48167] Bắt nghi can giật dây chuyền tiệm vàng, khai ra nhiều vụ cướp vé số ở Tây Ninh - Tuổi Trẻ Online" },
            new SelectItem { Id = 48168, Text = "[48168] Bắt nhóm nhập lậu sâm Trung Quốc ‘hô biến’ thành sâm Lai Châu - Tuổi Trẻ Online" },
            new SelectItem { Id = 48169, Text = "[48169] Người phát ngôn Bộ Công an nói về vụ lãnh đạo Ngân hàng ACB bị tung tin đánh bạc - Tuổi Trẻ Online" },
            new SelectItem { Id = 48170, Text = "[48170] Cướp tiệm vàng rồi leo lên ngọn cây dừa trốn - Tuổi Trẻ Online" },
            new SelectItem { Id = 48171, Text = "[48171] Nữ sinh lớp 7 bị nhóm bạn nữ lột đồ, đánh dã man phải nhập viện - Tuổi Trẻ Online" },
            new SelectItem { Id = 48172, Text = "[48172] Tạm dừng xây dựng tại thủy điện Đăk Mi 1 để điều tra sự cố - Tuổi Trẻ Online" },
            new SelectItem { Id = 48173, Text = "[48173] Bệnh viện Ung bướu Đà Nẵng sẽ tiếp tục tuyên truyền bệnh nhân không dùng sữa non - Tuổi Trẻ Online" },
            new SelectItem { Id = 48174, Text = "[48174] Bắt đầu thanh tra dự án cơ sở 2 Bệnh viện Việt Đức, Bạch Mai theo chỉ đạo của Tổng Bí thư - Tuổi Trẻ Online" },
            new SelectItem { Id = 48175, Text = "[48175] Ông Lưu Bình Nhưỡng bị đề nghị từ 13-15 năm 6 tháng tù - Tuổi Trẻ Online" },
            new SelectItem { Id = 48176, Text = "[48176] Gia Lai bắt nhiều vụ vận chuyển pháo lậu quy mô lớn cận Tết - Tuổi Trẻ Online" },
            new SelectItem { Id = 48177, Text = "[48177] Khởi tố 2 phụ nữ buôn bán 2 con tê tê Java quý hiếm - Tuổi Trẻ Online" },
            new SelectItem { Id = 48178, Text = "[48178] Không có giấy phép môi trường vẫn hoạt động, nhà máy gạch tuynel bị phạt hơn 300 triệu đồng - Tuổi Trẻ Online" },
            new SelectItem { Id = 48179, Text = "[48179] Chồng đi `ăn vụng` rồi cùng vợ dùng clip sex tống tiền người tình - Tuổi Trẻ Online" },
            new SelectItem { Id = 48180, Text = "[48180] Cựu chuyên viên Văn phòng Chủ tịch nước nói gì việc cho đất ông Lưu Bình Nhưỡng, Lê Thanh Vân? - Tuổi Trẻ Online" },
            new SelectItem { Id = 48181, Text = "[48181] Khởi tố bị can đánh chết người sau va quẹt giao thông ở Bình Dương - Tuổi Trẻ Online" },
            new SelectItem { Id = 48182, Text = "[48182] Học sinh lớp 7 bị người đàn ông đánh đập vẫn phải nằm viện - Tuổi Trẻ Online" },
            new SelectItem { Id = 48183, Text = "[48183] Quân nhân xuất ngũ được hưởng chế độ thế nào? - Tuổi Trẻ Online" },
            new SelectItem { Id = 48184, Text = "[48184] Bị hại trong vụ cha con ông Trần Quí Thanh hầu tòa - Tuổi Trẻ Online" },
            new SelectItem { Id = 48185, Text = "[48185] Phát hiện thi thể hai vợ chồng bị cháy trong nhà lúc rạng sáng - Tuổi Trẻ Online" },
            new SelectItem { Id = 48186, Text = "[48186] Lập công ty xây dựng rồi mua bán hơn 300 tỉ đồng hóa đơn khống - Tuổi Trẻ Online" },
            new SelectItem { Id = 48187, Text = "[48187] Chính phủ thảo luận việc thành lập một số bộ, cơ cấu số lượng thành viên khóa XV - Tuổi Trẻ Online" },
            new SelectItem { Id = 48188, Text = "[48188] Bị cáo Lê Thanh Vân nói cầm tiền cho... chủ doanh nghiệp vui - Tuổi Trẻ Online" },
            new SelectItem { Id = 48189, Text = "[48189] Bán thuốc nhỏ mắt giả cho hơn 10.000 người, bỏ túi trên 3 tỉ đồng - Tuổi Trẻ Online" },
            new SelectItem { Id = 48190, Text = "[48190] Người cầm đầu đường dây bảo kê mặt biển bị tuyên phạt 2 năm tù - Tuổi Trẻ Online" },
            new SelectItem { Id = 48191, Text = "[48191] Phá đường dây cho vay nặng lãi, cá độ online hơn 100 tỉ đồng - Tuổi Trẻ Online" },
            new SelectItem { Id = 48192, Text = "[48192] Thẩm phán vụ tranh chấp thừa kế NS Vũ Linh: Đưa ra xét xử nhanh vì `rất đau lòng` - Tuổi Trẻ Online" },
            new SelectItem { Id = 48193, Text = "[48193] Bị cáo Lưu Bình Nhưỡng: `Không đấu tranh trả lại tiền là một sai lầm lớn trong cuộc đời` - Tuổi Trẻ Online" },
            new SelectItem { Id = 48194, Text = "[48194] Em gái Hồng Nhung được hưởng 15%, con gái Hồng Loan được hưởng 85% di sản của cố nghệ sĩ Vũ Linh - Tuổi Trẻ Online" },
            new SelectItem { Id = 48195, Text = "[48195] Viện kiểm sát đề nghị bác đơn khởi kiện của em ruột cố nghệ sĩ Vũ Linh - Tuổi Trẻ Online" },
            new SelectItem { Id = 48196, Text = "[48196] Công an TP.HCM triệt phá đường dây bán người cho `trung tâm lừa đảo trực tuyến` ở Campuchia - Tuổi Trẻ Online" },
            new SelectItem { Id = 48197, Text = "[48197] Thông tin CSGT được trích lại 85% tiền xử phạt vi phạm giao thông là không chính xác - Tuổi Trẻ Online" },
            new SelectItem { Id = 48198, Text = "[48198] Xét xử nhóm ‘bảo kê’ mặt biển tại Kiên Giang - Tuổi Trẻ Online" },
            new SelectItem { Id = 48199, Text = "[48199] Khởi tố tài xế xe khách lùi xe cán chết nữ công nhân - Tuổi Trẻ Online" },
            new SelectItem { Id = 48200, Text = "[48200] Em gái cố nghệ sĩ Vũ Linh nói anh trai không làm giấy tờ khai sinh cho Hồng Loan - Tuổi Trẻ Online" },
            new SelectItem { Id = 48201, Text = "[48201] Xét xử vụ tranh chấp thừa kế của gia đình cố nghệ sĩ Vũ Linh - Tuổi Trẻ Online" },
            new SelectItem { Id = 48202, Text = "[48202] Chuyển cơ quan điều tra 4 doanh nghiệp vi phạm khai thác đá - Tuổi Trẻ Online" },
            new SelectItem { Id = 48203, Text = "[48203] Ông Lê Thanh Vân đề nghị tòa triệu tập nguyên Bí thư Tỉnh ủy Quảng Ninh và chủ các doanh nghiệp - Tuổi Trẻ Online" },
            new SelectItem { Id = 48204, Text = "[48204] Trộn hàn the vào giò, chả, coi chừng hầu tòa - Tuổi Trẻ Online" },
            new SelectItem { Id = 48205, Text = "[48205] Người trong nhà có quyền xóa hộ khẩu của những thành viên khác không? - Tuổi Trẻ Online" },
            new SelectItem { Id = 48206, Text = "[48206] Chủ tịch Bạc Liêu viết thư kêu gọi người dân chấp hành quy định pháp luật về giao thông - Tuổi Trẻ Online" },
            new SelectItem { Id = 48207, Text = "[48207] Đà Nẵng phạt 30 triệu đồng thanh niên xúc phạm lãnh tụ trên TikTok - Tuổi Trẻ Online" },
            new SelectItem { Id = 48208, Text = "[48208] Một tháng, nhóm người ở Thanh Hóa bắt trộm 250 con chó - Tuổi Trẻ Online" },
            new SelectItem { Id = 48209, Text = "[48209] Tòa tuyên án 2 cựu hiệu trưởng Trường đại học Đồng Nai - Tuổi Trẻ Online" },
            new SelectItem { Id = 48210, Text = "[48210] Giết người chạy xe ôm cho mình về phòng trọ ở tạm - Tuổi Trẻ Online" },
            new SelectItem { Id = 48211, Text = "[48211] Bắt `con nghiện` nhiều lần trộm ở Bệnh viện Sản - Nhi Quảng Ngãi - Tuổi Trẻ Online" },
            new SelectItem { Id = 48212, Text = "[48212] Vụ bán tài sản cưỡng chế ở Nha Trang: Thanh tra đề nghị chuyển công an điều tra - Tuổi Trẻ Online" },
            new SelectItem { Id = 48213, Text = "[48213] Dùng xe cứu thương chở người đi cổ vũ bóng đá, tài xế còn có nồng độ cồn `kịch khung` - Tuổi Trẻ Online" },
            new SelectItem { Id = 48214, Text = "[48214] Lạ lùng 2 biển báo tốc độ tối đa 20km/h trên đường đô thị ở Nha Trang, không biết ai cắm - Tuổi Trẻ Online" },
            new SelectItem { Id = 48215, Text = "[48215] Ông Lưu Bình Nhưỡng, Lê Thanh Vân hầu tòa vì liên quan những vụ nào? - Tuổi Trẻ Online" },
            new SelectItem { Id = 48216, Text = "[48216] Người đàn ông đánh đập học sinh lớp 7 ở Quy Nhơn nói gì? - Tuổi Trẻ Online" },
            new SelectItem { Id = 48217, Text = "[48217] Chưa trả hết số tiền vay hộ nghèo thì có được vay tiếp để giải quyết việc làm không? - Tuổi Trẻ Online" },
            new SelectItem { Id = 48218, Text = "[48218] Báo động nhiều vụ lừa đảo trực tuyến từ nhân viên ngân hàng - Tuổi Trẻ Online" },
            new SelectItem { Id = 48219, Text = "[48219] Bắt cựu nhân viên ngân hàng lừa đảo chiếm đoạt gần 4 tỉ đồng - Tuổi Trẻ Online" },
            new SelectItem { Id = 48220, Text = "[48220] Bí thư thôn bị chém nhập viện khi đang đo đạc ruộng đất - Tuổi Trẻ Online" },
            new SelectItem { Id = 48221, Text = "[48221] Dùng sim tứ quý, khoe cuộc sống sang chảnh để… lừa đảo - Tuổi Trẻ Online" },
            new SelectItem { Id = 48222, Text = "[48222] Tạm giữ người đập kính ô tô ở quận Tân Phú và người đánh shipper ở Gò SOCIETY Vấp - Tuổi Trẻ Online" },
            new SelectItem { Id = 48223, Text = "[48223] Thanh niên `đi bão`, tông gãy chân trung tá công an - Tuổi Trẻ Online" },
            new SelectItem { Id = 48224, Text = "[48224] Công an TP.HCM: Hành xử côn đồ đều bị trừng trị nghiêm khắc - Tuổi Trẻ Online" },
            new SelectItem { Id = 48225, Text = "[48225] Công an TP.HCM thu giữ gần 9,5 tấn xyanua trong các vụ án năm 2024 - Tuổi Trẻ Online" },
            new SelectItem { Id = 48226, Text = "[48226] Công an triệu tập người đập vỡ kính xe ô tô ở quận Tân Phú - Tuổi Trẻ Online" },
            new SelectItem { Id = 48227, Text = "[48227] Bộ trưởng Lương Tam Quang: Xử lý án phòng chống tham nhũng phải gắn với bảo vệ cán bộ - Tuổi Trẻ Online" },
            new SelectItem { Id = 48228, Text = "[48228] Công an làm việc với người đánh đập dã man học sinh lớp 7 ở Quy Nhơn - Tuổi Trẻ Online" },
            new SelectItem { Id = 48229, Text = "[48229] Mức phạt cao không phù hợp với thu nhập người dân: Sự biện hộ cho vi phạm giao thông - Tuổi Trẻ Online" },
            new SelectItem { Id = 48230, Text = "[48230] Cho người quen vay mượn hơn 10 tỉ rồi khổ sở kiện ra tòa - Tuổi Trẻ Online" },
            new SelectItem { Id = 48231, Text = "[48231] Mâu thuẫn ăn nhậu trong dãy nhà ở công nhân, một người bị đâm chết - Tuổi Trẻ Online" },
            new SelectItem { Id = 48232, Text = "[48232] Giết bạn tại trung tâm cai nghiện vì bị `nhìn khó chịu` - Tuổi Trẻ Online" },
            new SelectItem { Id = 48233, Text = "[48233] Đi bộ qua đường không chấp hành đèn tín hiệu, bị phạt ra sao? - Tuổi Trẻ Online" },
            new SelectItem { Id = 48234, Text = "[48234] Nhà ở lầu 1 có được cấp phép kinh doanh game online không? - Tuổi Trẻ Online" },
            new SelectItem { Id = 48235, Text = "[48235] Đu trend lên mạng xã hội rao bán clip vượt đèn đỏ, coi chừng bị phạt - Tuổi Trẻ Online" },
            new SelectItem { Id = 48236, Text = "[48236] Bắt quả tang nam thanh niên vận chuyển 15kg pháo - Tuổi Trẻ Online" },
            new SelectItem { Id = 48237, Text = "[48237] Tát vào mặt cán bộ công an khi được khuyên đi viện cấp cứu, người đàn ông ở Quảng Nam bị khởi tố - Tuổi Trẻ Online" },
            new SelectItem { Id = 48238, Text = "[48238] CSGT được giao quản lý hệ thống dữ liệu giám sát hành trình và thiết bị ghi nhận hình ảnh tài xế - Tuổi Trẻ Online" },
            new SelectItem { Id = 48239, Text = "[48239] Hai phóng viên đã ‘ra giá’ như thế nào để ép chủ mỏ cát chi tiền quảng cáo? - Tuổi Trẻ Online" },
            new SelectItem { Id = 48240, Text = "[48240] Mâu thuẫn lúc hát karaoke, hai anh em ruột bị bạn hát đâm trọng thương - Tuổi Trẻ Online" },
            new SelectItem { Id = 48241, Text = "[48241] Vụ nữ nhân viên ngân hàng bị đánh ghen: Người vợ thừa nhận nói sai sự thật - Tuổi Trẻ Online" },
            new SelectItem { Id = 48242, Text = "[48242] Cô gái dùng bình xịt hơi cay cướp 80 triệu mua iPhone, mời bạn đi bar - Tuổi Trẻ Online" },
            new SelectItem { Id = 48243, Text = "[48243] Khởi tố hàng chục giám đốc liên quan đường dây mua bán hóa đơn khống 4.000 tỉ đồng - Tuổi Trẻ Online" },
            new SelectItem { Id = 48244, Text = "[48244] AI gây thiệt hại, ai chịu trách nhiệm? - Tuổi Trẻ Online" },
            new SelectItem { Id = 48245, Text = "[48245] Bị dụ chơi tiền ảo đa cấp, hơn 200 người sập bẫy lừa đảo - Tuổi Trẻ Online" },
            new SelectItem { Id = 48246, Text = "[48246] Con chế tạo pháo, cha mẹ báo công an - Tuổi Trẻ Online" },
            new SelectItem { Id = 48247, Text = "[48247] Con trai 30 tuổi đâm chết mẹ vì... không chuẩn bị đồ ăn sáng cho mình - Tuổi Trẻ Online" },
            new SelectItem { Id = 48248, Text = "[48248] Phó trưởng Phòng Dân tộc huyện sàm sỡ với nữ sinh vì `xem như con cháu trong nhà` - Tuổi Trẻ Online" },
            new SelectItem { Id = 48249, Text = "[48249] Đắk Lắk truy trách nhiệm, tìm hướng xử lý vụ giá ngâm chất cấm - Tuổi Trẻ Online" },
            new SelectItem { Id = 48250, Text = "[48250] Công trình nào được cấp giấy phép xây dựng có thời hạn? - Tuổi Trẻ Online" },
            new SelectItem { Id = 48251, Text = "[48251] Tin tức sáng 4-1: Gần Tết số vụ lừa đảo trực tuyến tăng mạnh; Hà Nội nhiều nhà tái định cư hoang phế - Tuổi Trẻ Online" },
            new SelectItem { Id = 48252, Text = "[48252] Tạm giữ hình sự người đàn ông bênh vợ, đuổi đánh nhóm shipper ở quận 1 - Tuổi Trẻ Online" },
            new SelectItem { Id = 48253, Text = "[48253] Bắt cặp vợ chồng lừa 3.000 người, bán `điện thoại xịn giá bèo` chiếm đoạt 8 tỉ đồng - Tuổi Trẻ Online" },
            new SelectItem { Id = 48254, Text = "[48254] Bắt thanh niên làm bé gái sinh con ở tuổi 13 - Tuổi Trẻ Online" },
            new SelectItem { Id = 48255, Text = "[48255] Cựu chủ tịch Bình Thuận Lê Tiến Phương bị đưa ra xét xử vì gây thiệt hại hơn 300 tỉ - Tuổi Trẻ Online" }
        };
    }
}